using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Movie_website.BusinessLogic;
using Movie_website.ViewModels;

/*
 * HomeController
 * 
 * This controller is responsible for showing the homepage and general pages like Privacy and Error.
 * 
 * What it does:
 * - Shows the homepage with movies and series grouped by genre (Index method)
 * - Shows the privacy page (Privacy method)
 * - Shows the error page if something goes wrong (Error method)
 * 
 * Some methods are async because they need to fetch data from the API.
 * Other methods are not async when they just return a view without needing to fetch data.
 */

namespace Movie_website.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHomeLogic _homeLogic;

        /*
         * Constructor
         * 
         * Initializes the HomeLogic service to interact with the business logic layer.
         */
        public HomeController(IHomeLogic homeLogic)
        {
            _homeLogic = homeLogic;
        }

        /*
         * Index()
         * 
         * Fetches the homepage data, including movies and series for the specified genres.
         * It displays a preview of 6 movies/series per genre on the homepage.
         * 
         * This method is asynchronous as it fetches data from external services.
         */
        public async Task<IActionResult> Index()
        {
            // Fetch the homepage data through business logic
            var homepageViewModel = await _homeLogic.GetHomePageDataAsync();

            // Return the final viewmodel to be rendered in the view
            return View(homepageViewModel);
        }


        /**************************************************************************
         * The following methods are autogenerated
         **************************************************************************/

        /*
         * Privacy()
         * 
         * This method shows the Privacy page.
         * It is not async because it does not need to fetch data.
         */
        public IActionResult Privacy()
        {
            return View();
        }

        /*
         * Error()
         * 
         * This method shows the Error page if something goes wrong.
         * It creates an ErrorViewModel that contains a RequestId to help identify the error.
         * 
         * It is not async because it only creates an object and returns a view — no need to wait for external data.
         */
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            // return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });

            // Create a new ErrorViewModel object
            ErrorViewModel errorModel = new ErrorViewModel();

            // Check if Activity.Current is not null
            if (Activity.Current != null)
            {
                // Set the RequestId to the current Activity Id
                errorModel.RequestId = Activity.Current.Id;
            }
            else
            {
                // If Activity.Current is null, use the HttpContext TraceIdentifier
                errorModel.RequestId = HttpContext.TraceIdentifier;
            }

            // Pass the model to the View
            return View(errorModel);
        }
    }
}
