/** 
 * This method is autogenerated
 * 
 * ErrorViewModel
 * 
 * This model represents the data structure used to display error details on the error page.
 * It contains information about the RequestId to help with debugging and identifying errors.
 * 
 * Why we have it: This ViewModel is used in the error page to show a user-friendly error message 
 * and display the RequestId for developers to trace the error. The `ShowRequestId` property helps to
 * conditionally display the RequestId based on whether it's present or not.
 */

namespace Movie_website.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        // Checks if RequestId exists, and if it does, it will be shown in the error message
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}
